package Sample

// The code in this file is autogenerated, do not modify manually!

import (
	"bytes"
	"encoding/gob"
	"sync"

	. "github.com/rah-0/hyperion/register"
)

const (
	Version    = "v1"
	Name       = "Sample"
	DbFileName = "SampleV1.bin"
)

var Fields = map[string]int{
	"Name":    1,
	"Surname": 2,
}

var (
	_       Model = (*Sample)(nil)
	mu      sync.Mutex
	Buffer  = new(bytes.Buffer)
	Encoder = gob.NewEncoder(Buffer)
	Decoder = gob.NewDecoder(Buffer)
)

func init() {
	gob.Register(Sample{})

	RegisterEntity(&Entity{
		Version:    Version,
		Name:       Name,
		DbFileName: DbFileName,
		Fields:     Fields,
		New:        New,
	})
}

type Sample struct {
	Name    string
	Surname string
}

func New() Model {
	return &Sample{}
}

func (s *Sample) SetFieldValue(fieldName string, value any) {
	switch Fields[fieldName] {
	case 1:
		if v, ok := value.(string); ok {
			s.Name = v
		}
	case 2:
		if v, ok := value.(string); ok {
			s.Surname = v
		}
	}
}

func (s *Sample) GetFieldValue(fieldName string) any {
	switch Fields[fieldName] {
	case 1:
		return s.Name
	case 2:
		return s.Surname
	}
	return nil
}

func (s *Sample) Encode() error {
	mu.Lock()
	defer mu.Unlock()
	return Encoder.Encode(s)
}

func (s *Sample) Decode() error {
	mu.Lock()
	defer mu.Unlock()
	return Decoder.Decode(s)
}

func (s *Sample) BufferReset() {
	mu.Lock()
	defer mu.Unlock()
	Buffer.Reset()
}
