package Sample

// The code in this file is autogenerated, do not modify manually!

import (
	"encoding/gob"
)

func init() {
	gob.Register(Sample{})
}

const (
	Version = "v2"
)

type Sample struct {
	FullName string
}
